[project]
name = "server"
version = "0.1.0"
description = "Backend do sistema Usuários"
requires-python = ">=3.13"
dependencies = [
    "argon2-cffi>=25.1.0",
    "fastapi>=0.136.1",
    "pydantic[email]>=2.13.4",
    "pyjwt>=2.13.0",
    "pymysql>=1.2.0",
    "python-dotenv>=1.2.2",
    "sqlmodel>=0.0.38",
    "uvicorn>=0.47.0",
]
